// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    'ascii-spinner-animation': string;
    'ascii_spinner': string;
    'loading-spinner': string;
    'show-spinner-animation': string;
    'spinner_image': string;
    'spinner_wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
