// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    'empty': string;
    'empty__header': string;
    'empty__image': string;
    'empty__text': string;
}
export const cssExports: CssExports;
export default cssExports;
