// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    'is_hidden': string;
    'is_hidden__hidden': string;
}
export const cssExports: CssExports;
export default cssExports;
