// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    'error_data': string;
    'error_data__text': string;
}
export const cssExports: CssExports;
export default cssExports;
