// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    'glitch': string;
    'glitch-effect-animation': string;
    'page_404_header': string;
}
export const cssExports: CssExports;
export default cssExports;
